version: "3.9"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: panel
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build: .
    command: flask run --host=0.0.0.0 --port=5000 --reload
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: app
      FLASK_ENV: development   # включает debug и reload
      DATABASE_URL: postgresql://postgres:postgres@db:5432/panel
      SECRET_KEY: supersecretkey
    depends_on:
      - db
    volumes:
      - .:/app                  # монтируем код для горячей перезагрузки
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  pgdata:
